# Generated by Django 5.1.6 on 2025-03-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('parqueos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('parqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parqueos.parqueo')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
