# Generated by Django 5.1.6 on 2025-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Automovil', 'automovil'), ('Moto', 'moto')], max_length=10)),
                ('estado', models.CharField(choices=[('Libre', 'libre'), ('Ocupado', 'ocupado'), ('Reservado', 'reservado')], default='Libre', max_length=10)),
            ],
            options={
                'db_table': 'celdas',
            },
        ),
    ]
