# Generated by Django 5.1.6 on 2025-03-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celdas', '0001_initial'),
        ('tarifas', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'activo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=10)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celdas.celda')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tarifas.tarifa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'parqueos',
            },
        ),
    ]
