# Generated by Django 5.1.6 on 2025-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Hora', 'Por Hora'), ('Mes', 'mes')], max_length=10)),
                ('vehiculo_tipo', models.CharField(choices=[('Automovil', 'automovil'), ('Moto', 'moto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tarifas',
            },
        ),
    ]
